name: OSSAR Security Analysis

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run OSSAR analysis weekly on Monday at 3 AM UTC
    - cron: '0 3 * * 1'
  workflow_dispatch:

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  ossar:
    name: OSSAR Multi-Tool Security Analysis
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build shared packages
        run: |
          npm run build --workspace=packages/shared
          npm run build --workspace=packages/database
          
      - name: Run OSSAR
        uses: github/ossar-action@v1
        id: ossar
        
      - name: Upload OSSAR results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ steps.ossar.outputs.sarifFile }}
          
      - name: Upload OSSAR results as artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ossar-results
          path: ${{ steps.ossar.outputs.sarifFile }}
          retention-days: 30